---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel9:latest
    pull: missing 

dependencies:
  # Use python3
  python_interpreter:
    package_system: python3
    python_path: /usr/bin/python3

  ansible_core:
    package_pip: ansible-core

  ansible_runner:
    package_pip: ansible-runner

  system:
    - openssh-clients
    - sshpass
    - gcc
    - systemd-devel
    - libxml2-devel
    - python3-devel

  # python:
  #   - ansible-navigator
  #   - boto3
  #   - requests

  galaxy:
    collections:
      - name: community.libvirt
  
  # additional_build_files:
  #   - src: 
  # additional_build_steps:
  #   append_base:
  #     - RUN $PYCMD -m pip install -U pip

# options:
  #   tags:
  #     - ansible_sample_ee
