---
# General VM settings
libvirt_pool_dir: "/var/lib/libvirt/images"
# vm_memory: 2048
# vm_vcpus: 2
vm_network: demo.net
vm_storage_pool: default
vm_os_image_path: "/var/lib/libvirt/images/rhel-9.7-x86_64-kvm.qcow2"
vm_root_pass: "redhat"   # Change this to a secure password
ssh_key_path: "/root/.ssh/id_rsa.pub"


# List of VMs to create
vms:
- name: idm.demo.net
  ip_address: 192.168.25.10
  gateway: 192.168.25.1
  dns_servers:
    - 192.168.25.1
  disk_size: 10G
  vm_memory: 4096
  vm_vcpus: 2
- name: satellite.demo.net
  ip_address: 192.168.25.11
  gateway: 192.168.25.1
  dns_servers:
    - 192.168.25.10
  disk_size: 100G
  vm_memory: 24576
  vm_vcpus: 4